"""Adiciona email ao Client

Revision ID: 3fce1ea6a22c
Revises: fc9e1791c086
Create Date: 2025-11-08 06:13:11.720382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fce1ea6a22c'
down_revision = 'fc9e1791c086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_client_email', ['email'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('uq_client_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
