"""Add date field to Task

Revision ID: 833ee222c7f4
Revises: 
Create Date: 2025-04-26 21:25:29.070514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833ee222c7f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('done', sa.Boolean(), nullable=True, default=False))  # Reintroduzir 'done'
        batch_op.add_column(sa.Column('done_comment', sa.String(length=300), nullable=True))  # Adicionar 'done_comment'

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('done_comment')  # Remover 'done_comment'
        batch_op.drop_column('done')  # Remover 'done'
        batch_op.drop_column('date')

    # ### end Alembic commands ###
