"""Adiciona roles, nome e atribuição de tecnicos

Revision ID: fc9e1791c086
Revises: 
Create Date: 2025-11-06 19:52:48.401925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9e1791c086'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technician_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_todo_technician_id', 'user', ['technician_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('name')

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_todo_technician_id', type_='foreignkey')
        batch_op.drop_column('technician_id')

    # ### end Alembic commands ###
